name: Run Tests
on:
  push:
    branches:
      - main  # This is your deployment branch

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.4'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest 


  ssh-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
      - name: Connect via SSH
        run: ssh -o StrictHostKeyChecking=no username@${{ secrets.SSH_HOST }}
        

      
  deploy-on-droplet:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Execute Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/farm
            git pull https://github.com/IamTravolta/cd-winc.git
            systemctl restart farm
            systemctl status farm
            echo "Deployment Test Completed"
          timeout: 30s
          command_timeout: 10m

                  