name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Set this to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_TOKEN }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "157.230.124.163" >> ~/.ssh/known_hosts
    
    - name: Run tests
      run: |
        # Add commands to run your tests here
        echo "Running tests..."
        # Example: npm test
    
    - name: Deploy to Droplet
      run: |
            host: ${{ secrets.SSH_HOST }} 
            password: ${{ secrets.SSH_PRIVATE_KEY }}
            username: ${{ secrets.SSH_USERNAME }}
            port: ${{ secrets.SSH_PORT }}
      env:
        SSH_KEY: ${{ secrets.SSH_TOKEN }}
        script: |
            cd /home/farm
            git init .
            git clone git@github.com:M https://github.com/IamTravolta/cd-winc
            git pull
            systemctl restart farm
            systemctl status farm
            echo "Test"
