name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Set this to your deployment branch

jobs:
        deploy:
          runs-on: ubuntu-latest
          steps:
          - name: Checkout code
            uses: actions/checkout@v2
          
          - name: Set up SSH
            run: |
              mkdir -p ~/.ssh
              echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
      
          - name: Debug SSH connection
            run: |
              ssh -vvv -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.DROPLET_IP }} "echo 'SSH Connection Successful'"
      
          - name: Set Git Branch and Pull Changes
            run: |
              ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.DROPLET_IP }} "cd /home/farm && git branch --set-upstream-to=origin/main main && git pull"
      