name: Run Tests
on:
  push:
    branches:
      - main  # This is the deployment branch

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.4'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest 

    
  deploy-on-droplet:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Execute Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/farm
            git pull https://github.com/IamTravolta/cd-winc.git
            systemctl restart farm
            systemctl status farm
            systemctl restart nginx
            echo "Deployment Test Completed"
          timeout: 30s
          command_timeout: 10m

                  